import './App.css';

import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "./schema"; // generated by openapi-typescript

const fetchClient = createFetchClient<paths>({
  baseUrl: "http://localhost:3000",
});
const $api = createClient(fetchClient);

function App() {
  const { data, error, isLoading } = $api.useQuery('get', '/wishlist/{name}', {
    params: { path: { name: 'Mike' } },
  })

  if (isLoading) return <p>Loading...</p>

  if (error) return <p>Error: {error}</p>

  return (
    <>
      <p>Wishlist for <b>{data?.recipient}</b></p>

      <ul>
        {data?.items.map((wishlistItem, index) => (
          <li key={index}>
            {wishlistItem.item} - ${wishlistItem.ecommerceUrl}
          </li>
        ))}
      </ul>
    </>
  )
}

export default App
