import './App.css';

import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "./schema"; // generated by openapi-typescript
import { useState } from 'react';

const fetchClient = createFetchClient<paths>({
  baseUrl: "http://localhost:3000",
});
const $api = createClient(fetchClient);

function App() {
  const [name, setName] = useState('')

  const { data, error, isLoading } = $api.useQuery('get', '/wishlist/{name}', {
    params: { path: { name } },
  })

  if (isLoading || !data) return (
    <>
      <p>Waiting for data...</p>
      <p>Wishlist for <input type="text" value={name} onChange={(e) => setName(e.target.value)} /></p>
    </>
  )

  if (error) return <p>Error: {error}</p>

  return (
    <>
      <p>Wishlist for <input type="text" value={name} onChange={(e) => setName(e.target.value)} /></p>

      <ul>
        {data?.items.map((wishlistItem, index) => (
          <li key={index}>
            <a href={wishlistItem.ecommerceUrl}>{wishlistItem.item}</a>
          </li>
        ))}
      </ul>
    </>
  )
}

export default App
