/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["AppController_getHello"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wishlist": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Create a new wishlist. */
        post: operations["WishlistController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/wishlist/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Retrieve the wishlist given the recipient's name. */
        get: operations["WishlistController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        WishlistItem: {
            /** @description Name or description of the item. */
            item: string;
            /**
             * @description URL to the item in any ecommerce site.
             * @example https://apple.com
             */
            ecommerceUrl: string;
        };
        WishlistCreationDto: {
            /**
             * @description The items in the wishlist.
             * @default []
             * @example [
             *       {
             *         "item": "MacBook Pro 16\"",
             *         "ecommerceUrl": "https://www.apple.com/macbook-pro-16/"
             *       }
             *     ]
             */
            items: components["schemas"]["WishlistItem"][];
            /**
             * @description The name of the recipient of the wishlist.  Currently there's no authentication, and the
             *     wishlist is built on trust and honesty of S1 employees.
             * @example Juswa
             */
            recipient: string;
        };
        Wishlist: {
            /**
             * @description The items in the wishlist.
             * @default []
             * @example [
             *       {
             *         "item": "MacBook Pro 16\"",
             *         "ecommerceUrl": "https://www.apple.com/macbook-pro-16/"
             *       }
             *     ]
             */
            items: components["schemas"]["WishlistItem"][];
            /**
             * @description The ID of the wishlist.  It is unique and auto-incremented.
             * @example 14
             */
            id: number;
            /**
             * @description The name of the recipient of the wishlist.  Currently there's no authentication, and the
             *     wishlist is built on trust and honesty of S1 employees.
             * @example Juswa
             */
            recipient: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    AppController_getHello: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string;
                };
            };
        };
    };
    WishlistController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WishlistCreationDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Wishlist"];
                };
            };
        };
    };
    WishlistController_findAll: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Wishlist"];
                };
            };
        };
    };
}
